# Generated by Django 4.2.2 on 2023-07-06 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
    ]
